EasyCoding/urls.py
from django.contrib import admin
from django.urls import path, include
import django.contrib.auth.views as auth_view

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls'), name='account'),
    path('', views.home, name='home'),
    path('assessment/', include('assessment.urls'), name='assessment'),
    path('course/', include('course.urls'), name='course'),
    path('wiki/', include('wiki.urls'), name='wiki'),
    path('tutorial/', include('tutorial.urls'), name='tutorial'),
]

assessment/urls.py
from django.urls import path, include
from . import views

app_name = 'assessment'

urlpatterns = [
    path('', views.assessment, name="assessment_for_precess"),
    path('<int:pk>', views.assessment, name="assessment"),
    path('vote/<int:pk>', views.vote, name="vote"),
    path('vote/<int:pk>/<str:sort_by>', views.vote, name="vote"),
    path('vote/<int:pk>/<str:sort_by>/<int:page>', views.vote, name="vote"),
    path('assessment_add/<int:pk>', views.assessment_add, name="assessment_add"),
]

course/urls.py
from django.urls import path, include
from . import views

app_name = 'course'

urlpatterns = [
    path('', views.course, name="course_for_process"),
    path('<int:lesson_number>/<int:chapter>', views.course, name="course"),
    path('course_add/<int:lesson_number>/<int:chapter>', views.course_add, name="course_add")
]

wiki/urls.py
from django.urls import path, include
from . import views

app_name = 'wiki'

urlpatterns = [
    path('<int:lesson>/<int:chapter>', views.wiki, name="wiki"),
]

course/models.py
from django.db import models


# Create your models here.

class Lesson(models.Model):
    number = models.IntegerField(
        primary_key=True
    )

    name = models.CharField(
        max_length=100
    )

    @staticmethod
    def get_lesson_length():
        return len(Lesson.objects.all())

    def next_lesson(self):

        result = Lesson.objects.get(number=self.number + 1)
        return result

    def __str__(self):
        return "%d.%s" % (self.number, self.name)

    def __gt__(self, other):
        if isinstance(other, Lesson):
            if other.number == 0:
                return False
            else:
                return self.number > other.number
        else:
            raise TypeError()

    def __ge__(self, other):
        return self > other or self == other

    def __lt__(self, other):
        if isinstance(other, Lesson):
            if other.number == 0:
                return False
            else:
                return self.number < other.number
        else:
            raise TypeError()

    def __add__(self, other):
        if isinstance(other, int):
            temp = self.number + other
            if temp > Lesson.get_lesson_length():
                return Lesson.objects.get(number=temp)
            else:
                raise ValueError("out of range")
        else:
            raise TypeError()


class Course(models.Model):
    name = models.CharField(
        max_length=100,
    )

    lesson = models.ForeignKey(
        "Lesson",
        on_delete=models.CASCADE
    )

    chapter = models.IntegerField(
        default=0
    )

    def __str__(self):
        if self.chapter == 0:
            return str(self.name)

        return "%d-%d %s" % (self.lesson.number, self.chapter, str(self.name))

    def __gt__(self, other):
        if isinstance(other, Course):
            if other.lesson.number == self.lesson.number == 0:
                return self.chapter > other.chapter
            elif other.lesson.number == 0:
                return False
            elif self.lesson.number == 0:
                return False

            if self.lesson > other.lesson:
                return True
            elif self.lesson < other.lesson:
                return False
            else:
                return self.chapter > other.chapter
        else:
            raise TypeError()

    def __ge__(self, other):
        return self > other or self == other

    def __lt__(self, other):
        if isinstance(other, Course):
            if other.lesson.number == 0:
                return False
            elif self.lesson.number == 0:
                return False

            if self.lesson < other.lesson:
                return True
            elif self.lesson > other.lesson:
                return False
            else:
                return self.chapter < other.chapter
        else:
            raise TypeError()

    # def __add__(self, other):
    #     if isinstance(other, int):
    #         if other == 1:
    #             try:
    #                 result = Course.objects.get(lesson=self.lesson, chapter=self.chapter+1)
    #                 return result
    #             except Course.DoesNotExist:
    #
    #                 lesson = self.lesson + 1
    #                 chapter = 1
    #
    #                 return Course.objects.get(lesson=lesson, chapter=chapter)
    #
    #     else:
    #         raise TypeError("%s is not allow" % type(other))

    def next_course(self):

        try:
            result = Course.objects.get(lesson=self.lesson, chapter=self.chapter + 1)
            return result

        except Course.DoesNotExist:

            try:
                lesson = self.lesson.next_lesson()
                chapter = 1

                return Course.objects.get(lesson=lesson, chapter=chapter)
            except Lesson.DoesNotExist:

                return Course.complete_course()

    @staticmethod
    def complete_course():

        return Course.objects.get(lesson__number=100, chapter=0)


class Content(models.Model):
    content = models.TextField(
        max_length=4000
    )

    number = models.IntegerField(
        default=-1
    )

    isTitle = models.BooleanField(
        default=False
    )

    isSubTitle = models.BooleanField(
        default=False
    )

    isText = models.BooleanField(
        default=False
    )

    isCode = models.BooleanField(
        default=False
    )

    isImage = models.BooleanField(
        default=False
    )

    isLink = models.BooleanField(
        default=False
    )

    isTable = models.BooleanField(
        default=False
    )

    course = models.ForeignKey(
        "Course",
        on_delete=models.CASCADE,
        null=True
    )

    def reset_type(self):
        self.isTitle = False
        self.isSubTitle = False
        self.isText = False
        self.isCode = False
        self.isImage = False
        self.isLink = False
        self.isTable = False

    def __str__(self):
        return "%s第%d段" % (str(self.course), self.number)

    def __lt__(self, other):
        if isinstance(other, Content):
            return self.number < other.number

        return False


class Fill(models.Model):
    course = models.ForeignKey(
        "Course",
        on_delete=models.CASCADE
    )

    content = models.TextField(
        max_length=3000
    )

    question = models.TextField(
        max_length=3000,
        null=True
    )

    def __str__(self):
        return str(self.course)


class Fill_Answer(models.Model):
    answer = models.CharField(
        max_length=50
    )

    fill = models.ForeignKey(
        "Fill",
        on_delete=models.CASCADE,
        null=True
    )

    def __str__(self):
        return str(self.fill)

course/views.py
from django.shortcuts import render
from django.http.response import JsonResponse
from django.http import Http404
from django.contrib.auth.decorators import login_required

from .apps import CourseMenuContent, CourseAdmin, FillQuestion, compare_str
from .models import Course, Content, Fill_Answer, Lesson


# Create your views here.
@login_required
def course(request, lesson_number=-1, chapter=-1):
    user_course = request.user.course_progress

    if lesson_number == -1 and chapter == -1:
        lesson_number, chapter = user_course.lesson.number, user_course.chapter

    try:
        choice_course = Course.objects.get(lesson=lesson_number, chapter=chapter)
    except Course.DoesNotExist:
        if lesson_number < Lesson.get_lesson_length():
            chapter = 1
            lesson_number += 1
            choice_course = Course.objects.get(lesson=lesson_number, chapter=chapter)
        else:
            raise Http404("之後就沒囉!!")

    assessment_pk = False
    assessment_for_choice_course = choice_course.assessment_set.all().filter(level=1)

    if assessment_for_choice_course:
        assessment_pk = assessment_for_choice_course[0].pk

    if request.user.is_superuser:
        pass
    elif lesson_number > user_course.lesson.number:
        raise Http404("YOU SHALL NOT PASS!!!!")
    elif lesson_number == user_course.lesson.number:
        if chapter > user_course.chapter:
            raise Http404("YOU SHALL NOT PASS!!!!")

    if request.method == "GET":
        template = "course/course.html"

        all_content = list(Content.objects.filter(course=choice_course))
        all_content.sort()

        all_course_menu = []

        for i in Lesson.objects.all().exclude(number__gt=10).exclude(number__lt=1):
            all_course_menu.append(
                CourseMenuContent(i, user_course)
            )

        fill_question = FillQuestion(choice_course)

        return render(request, template, {"all_content": all_content,
                                          "course_name": str(choice_course),
                                          "all_course_menu": all_course_menu,
                                          "lesson": lesson_number,
                                          "chapter": chapter,
                                          "fill_question": fill_question,
                                          "assessment_pk": assessment_pk})

    user_answer = request.POST["answer"]
    fill_answers = Fill_Answer.objects.filter(fill__course=choice_course)

    is_answer_right = False
    which_false = [i for i in range(100)]

    for answer in fill_answers:

        is_answer_right, temp_which_false = compare_str(user_answer, answer.answer)

        if len(temp_which_false) < len(which_false):
            which_false = temp_which_false

        if is_answer_right:
            break

    is_assessment_exist = bool(assessment_pk)

    if is_answer_right:

        if choice_course == user_course and not is_assessment_exist:
            request.user.course_progress = choice_course.next_course()
            request.user.save()

    return JsonResponse({"is_answer_right": is_answer_right,
                         "which_false": which_false,
                         "is_assessment_exist": is_assessment_exist})


@login_required
def course_add(request, lesson_number=1, chapter=1):
    if not request.user.is_superuser:
        raise Http404("not exist")

    template = "course/seven.html"
    choice_course = Course.objects.get(lesson__number=lesson_number, chapter=chapter)

    if request.method == "GET":

        all_content = list(Content.objects.filter(course=choice_course))
        all_content.sort()

        all_course = []

        for i in Lesson.objects.all():
            all_course.append(
                CourseAdmin(i)
            )

        return render(request, template, {
            "all_content": all_content,
            "all_course": all_course,
            "lesson": lesson_number,
            "chapter": chapter
        })

    # data = request.POST.get("data[0][]")
    datas = dict(request.POST)
    number = int(datas["number"][0])
    size = len(choice_course.content_set.all())

    count = number if number > size else size

    for i in range(count):
        if i < number:
            data = datas["data[%d][]" % i]

            data_type = data[1]
            value = data[2]
        else:
            temp = Content.objects.get(course=choice_course, number=i)
            temp.delete()

            continue

        temp = Content.objects.get_or_create(course=choice_course, number=i)[0]

        temp.reset_type()

        if data_type == "text":
            temp.isText = True
        elif data_type == "code":
            temp.isCode = True
        elif data_type == "title":
            temp.isTitle = True
        elif data_type == "subtitle":
            temp.isSubTitle = True
        elif data_type == "image":
            temp.isImage = True
            if '/' in value:
                temp.content = value
            else:
                temp.content = "course_image/%d%d/%s" % (lesson_number, chapter, value)
            temp.save()
            continue

        temp.content = value

        temp.save()

    return JsonResponse({})

templates/course/course.html
{% extends 'base.html' %}

{% block title %}
    {{ course_name }}
{% endblock %}

{% load static %}

{% block csslink %}
    <link rel="stylesheet" href="{% static "css/course/caw.css" %}">
    <link rel="stylesheet" href="{% static "css/course/course.css" %}">
    <link rel="stylesheet" href="{% static "css/course/style.css" %}">
    <link rel="stylesheet" href="{% static "Scrollbar/jquery.mCustomScrollbar.css" %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"
          integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
{% endblock %}

{% block jslink %}
    <script src="{% static "Scrollbar/jquery.mousewheel.min.js" %}"></script>
    <script src="{% static "Scrollbar/jquery.mCustomScrollbar.js" %}"></script>
{% endblock %}

{% block content %}

    <!--contain start-->
    <div class="container-fluid">
        <div class="row">
            <div class="d-none d-md-block d-xl-block col-12 col-md-4 col-lg-3 bd-sidebar">
                <nav class="content collapse bd-links float" id="bd-docs-nav">
                    {% for course_menu in all_course_menu %}
                        <div class="bd-toc-item active">
                            <a class="bd-toc-link" data-toggle="collapse" role="button"
                               data-target="#collapse{{ course_menu.lesson.number }}"
                               aria-expanded="false" aria-controls="collapseOne" href="#">
                                {{ course_menu.lesson }}

                                {% if course_menu.is_lock %}
                                    <div class="lock-background text-center">
                                        <i class="fas fa-lock"></i>
                                    </div>
                                {% endif %}
                            </a>

                            <div id="collapse{{ course_menu.lesson.number }}" class="collapse">
                                <ul class="nav bd-sidenav" aria-labelledby="headingOne">
                                    {% for course in course_menu.courses %}
                                        <li>
                                            {% if course.is_lock %}
                                                <a>
                                                    {{ course }}
                                                    <div class="lock-background text-center">
                                                        <i class="fas fa-lock"></i>
                                                    </div>
                                                </a>
                                            {% else %}
                                                <a href="{% url "course:course" course.lesson.number course.chapter %}">
                                                    {{ course }}
                                                </a>
                                            {% endif %}
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    {% endfor %}
                </nav>
            </div>

            <div id="course-wrapper" class="col-12 col-md-8 col-lg-9 cbd">
                <div class="float">

                    <h2>{{ course_name }}</h2>

                    <hr>

                    {% for content in all_content %}
                        {% if content.isTitle %}
                            <h5>
                                {{ content.content }}
                            </h5>
                        {% elif content.isSubTitle %}
                            <h6>
                                {{ content.content }}
                            </h6>
                        {% elif content.isText %}
                            <p class="word">{{ content.content }}</p>
                        {% elif content.isCode %}
                            <pre class="part">{{ content.content|safe }}</pre>
                        {% elif content.isImage %}
                            <p class="img"><img src="{% static content.content %}"></p>
                        {% elif content.isLink %}
                            <p class="wikilink">{{ content.content|safe }}</p>
                        {% elif content.isTable %}
                            <table class="tab">
                                {{ content.content|safe }}
                            </table>
                        {% endif %}
                    {% endfor %}

                    <div class="ex">
                        {{ fill_question.content|safe }}
                        <form id="fill-question" class="fill-question">
                            <div class="part">
                                {{ fill_question.question|safe }}
                            </div>

                            <button id="fill-answers-submit" type="button" class="btn btn-outline-dark">送出</button>
                            <button id="next-course" type="button" class="btn btn-outline-dark" style="display:none;">
                                下一課
                            </button>
                            <button id="goto-assessment" type="button" class="btn btn-outline-dark"
                                    style="display:none;">
                                寫作業
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--contain end-->

{% endblock %}

{% block tailjslink %}
    {% csrf_token %}
    <script>$.ajaxSetup({headers: {"X-CSRFToken": '{{ csrf_token }}'}});</script>

    <script type='text/javascript'>
        (function ($) {
            $(window).on("load", function () {
                $("#bd-sidebar").mCustomScrollbar();
                $(".content").mCustomScrollbar();
            });
        })(jQuery);

        let fill_question_input = $("#fill-question input");
        let fill_answers_submit = $("#fill-answers-submit");

        fill_question_input.keyup(function (e) {
            let code = e.keyCode || e.which;

            console.log("keyup:");
            console.log(code);

            if (code === 8 || code === 37 || code === 38) {
                $(this).prev().focus();
            } else if (code === 39 || code === 40) {
                $(this).next().focus();
            }
        });

        fill_question_input.keypress(function (e) {
            let code = e.keyCode || e.which;

            console.log("keypress:");
            console.log(code);

            if ((code >= 33 && code <= 126)) {
                $(this).next().focus();

                if ($(this).val()) {
                    $(this).next().val(e.key);
                }
            }

            if (code === 13) {
                e.preventDefault();

                if (fill_answers_submit.css("display") === "block") {
                    $("#fill-answers-submit").click();
                } else {
                    {% if assessment_pk %}
                        $("#goto-assessment").click();
                    {% else %}
                        $("#next-course").click();
                    {% endif %}
                }
            }
        });

        function answer_send() {

            let fill_form = $("#fill-question");

            let answer = "";

            fill_form.serializeArray().forEach(function (e) {
                if (e["value"] === "") {
                    answer += "~";
                } else {
                    answer += e["value"];
                }
            });

            $.ajax({
                type: "POST",
                data: {answer: answer},
                url: "{% url 'course:course' lesson chapter %}",
                cache: false,
                dataType: "json",
                success: function (result) {
                    console.log(result);

                    let all_input = $("#fill-question input");

                    let which_false = result["which_false"];

                    for (let i = 0; i < all_input.length; i++) {
                        let temp = $(all_input[i]);
                        temp.removeClass("default");
                        temp.removeClass("red");
                        temp.addClass("green");
                    }

                    which_false.forEach(function (e) {
                        let temp = $(all_input[e]);
                        temp.removeClass("default");
                        temp.removeClass("green");
                        temp.addClass("red");
                    });

                    let is_answer_right = result["is_answer_right"];
                    let is_assessment_exist = result["is_assessment_exist"];

                    if (is_answer_right) {
                        $("#fill-answers-submit").hide();

                        if (is_assessment_exist) {
                            $("#goto-assessment").show();
                        } else {
                            $("#next-course").show();
                        }
                    }
                },

                error: function () {
                    console.log(888);
                }
            });
        }

        fill_answers_submit.click(answer_send);

        $("#next-course").click(function () {
            window.location.href = "{% url "course:course" lesson chapter|add:'1' %}"
        });

        {% if assessment_pk %}
            $("#goto-assessment").click(function () {
                window.location.href = "{% url "assessment:assessment" assessment_pk %}"
            });
        {% endif %}
    </script>
{% endblock %}

templates/course/seven.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <title>test</title>
    <link rel="stylesheet" href="{% static "boot/bootstrap-4.0.0.css" %}">
    <link rel="stylesheet" href="{% static "css/course/play.css" %}">
    <link rel="stylesheet" href="{% static "css/course/course.css" %}">

    <script src="{% static "boot/jquery-3.2.1.min.js" %}"></script>
    <script src="{% static "boot/bootstrap.bundle.js" %}"></script>
    <script src="{% static "js/jquery-ui-1.12.1/jquery-ui.js" %}"></script>

    <script>
        $(function () {
            $("#sortable").sortable({
                placeholder: "ui-state-highlight"
            });
            $("#sortable").disableSelection();
        });
    </script>
</head>

<body>

<div class="container-fiuld">


    <div class="row" style="background-color: gray">
        <div class="d-none d-md-block d-xl-block col-12 col-md-4 col-lg-3 bd-sidebar">
            <nav class="content collapse bd-links float" id="bd-docs-nav">
                {% for course in all_course %}
                    <div class="bd-toc-item">
                        <a class="bd-toc-link" data-toggle="collapse" role="button"
                           data-target="#collapse-{{ course.lesson.number }}"
                           aria-expanded="false" aria-controls="collapse-{{ course.lesson.number }}" href="#">
                            {{ course.lesson }}
                        </a>

                        <div id="collapse-{{ course.lesson.number }}" class="collapse">
                            <ul class="nav bd-sidenav" aria-labelledby="headingOne">
                                {% for sub_course in course.data %}
                                    <li>
                                        <a href="{% url "course:course_add" sub_course.lesson.number sub_course.chapter %}">
                                            {{ sub_course }}
                                        </a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                {% endfor %}
            </nav>
        </div>

        <div class="col-12 col-md-8 col-lg-9 cbd">
            <ul id="sortable">
                {% for content in all_content %}
                    <li class="ui-state-default">
                        <div class="dropdown show"
                             data-type="{% if content.isTitle %}title{% elif content.isSubTitle %}subtitle{% elif content.isText %}text{% elif content.isCode %}code{% elif content.isImage %}image{% elif content.istable %}table{% endif %}">

                            <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false">
                                {% if content.isTitle %}
                                    title
                                {% elif content.isSubTitle %}
                                    subtitle
                                {% elif content.isText %}
                                    text
                                {% elif content.isCode %}
                                    code
                                {% elif content.isImage %}
                                    image
                                {% elif content.isTable %}
                                    table
                                {% endif %}</a>

                            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                <a class="dropdown-item" href="##">title</a>
                                <a class="dropdown-item" href="##">subtitle</a>
                                <a class="dropdown-item" href="##">text</a>
                                <a class="dropdown-item" href="##">code</a>
                                <a class="dropdown-item" href="##">image</a>
                                <a class="dropdown-item" href="##">table</a>
                            </div>

                            <button type="button" class="btn btn-danger remove" style="position: absolute;right:0;">刪除
                            </button>
                        </div>

                        <div class="content">
                            <textarea name="content-1" id="content-1">{{ content.content|safe }}</textarea>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>

        <div class="d-none d-md-block d-xl-block col-12 col-md-4 col-lg-3"></div>

        <div class="col-12 col-md-8 col-lg-9 cbd">

            <div class="row" style="padding: 15px">
                <div class="col">
                    <button id="add" type="button" class="btn btn-dark">新增</button>
                </div>
                <div class="col">
                    <button id="submit" type="button" class="btn btn-dark">送出</button>
                </div>
            </div>

        </div>
    </div>


</div>

{% csrf_token %}
<script>$.ajaxSetup({headers: {"X-CSRFToken": '{{ csrf_token }}'}});</script>
<script>
    $("#add").click(function () {

        $("#sortable").append(`<li class="ui-state-default">
                        <div class="dropdown show" data-type="text">
                            <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">text</a>

                            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                <a class="dropdown-item" href="##">title</a>
                                <a class="dropdown-item" href="##">subtitle</a>
                                <a class="dropdown-item" href="##">text</a>
                                <a class="dropdown-item" href="##">code</a>
                                <a class="dropdown-item" href="##">image</a>
                                <a class="dropdown-item" href="##">table</a>
                            </div>

                            <button type="button" class="btn btn-danger remove" style="position: absolute;right:0;">刪除</button>
                        </div>

                        <div class="content">
                            <textarea name="content-1" id="content-1"></textarea>
                        </div>
                    </li>`);

        $(".dropdown-item").click(function () {
            let a = $(this).parent().parent();

            a.attr("data-type", $(this).html());
            a.children("a").html($(this).html());
        });

        $(".remove").click(function () {
            let a = $(this).parent().parent();

            a.remove();
        });

    });

    $(".remove").click(function () {
        let a = $(this).parent().parent();

        a.remove();
    });

    $("#submit").click(function () {
        let a = $("#sortable > li");

        var arr = [];
        var number = a.length;

        for (let i = 0; i < a.length; i++) {
            let b = $(a[i]);

            let type = b.children(".dropdown").attr("data-type");
            let value = b.children(".content").children("textarea").val();

            arr.push([i, type, value])
        }

        console.log(arr);

        $.ajax({
            type: "POST",
            data: {data: arr, number: number},
            url: "{% url 'course:course_add' lesson chapter %}",
            cache: false,
            dataType: "json",
            success: function (result) {

                alert('bububu');

            },
            error: function () {
                alert(888);
            }
        });
    });

    $(".dropdown-item").click(function () {
        let a = $(this).parent().parent();

        a.attr("data-type", $(this).html());
        a.children("a").html($(this).html());

        if ($(this).html() == "image") {

        }
    });

</script>
</body>

</html>