EasyCoding/urls.py
from django.contrib import admin
from django.urls import path, include
import django.contrib.auth.views as auth_view

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls'), name='account'),
    path('', views.home, name='home'),
    path('assessment/', include('assessment.urls'), name='assessment'),
    path('course/', include('course.urls'), name='course'),
    path('wiki/', include('wiki.urls'), name='wiki'),
    path('tutorial/', include('tutorial.urls'), name='tutorial'),
]

assessment/urls.py
from django.urls import path, include
from . import views

app_name = 'assessment'

urlpatterns = [
    path('', views.assessment, name="assessment_for_precess"),
    path('<int:pk>', views.assessment, name="assessment"),
    path('vote/<int:pk>', views.vote, name="vote"),
    path('vote/<int:pk>/<str:sort_by>', views.vote, name="vote"),
    path('vote/<int:pk>/<str:sort_by>/<int:page>', views.vote, name="vote"),
    path('assessment_add/<int:pk>', views.assessment_add, name="assessment_add"),
]

wiki/urls.py
from django.urls import path, include
from . import views

app_name = 'wiki'

urlpatterns = [
    path('<int:lesson>/<int:chapter>', views.wiki, name="wiki"),
]

assessment/models.py
from django.db import models
from account.models import User
from course.models import Course


# Create your models here.

class Content(models.Model):
    number = models.IntegerField()

    content = models.TextField(
        max_length=2100
    )

    isTitle = models.BooleanField(
        default=False
    )

    isText = models.BooleanField(
        default=False
    )

    isCode = models.BooleanField(
        default=False
    )

    isImage = models.BooleanField(
        default=False
    )

    isLink = models.BooleanField(
        default=False
    )

    isTable = models.BooleanField(
        default=False
    )

    assessment = models.ForeignKey(
        "Assessment",
        on_delete=models.CASCADE
    )

    def reset_type(self):
        self.isTitle = False
        self.isSubTitle = False
        self.isText = False
        self.isCode = False
        self.isImage = False
        self.isLink = False
        self.isTable = False

    def __str__(self):
        return "%s第%d段" % (str(self.assessment), self.number)

    def __ge__(self, other):
        if isinstance(other, Content):
            return self.number > other.number
        else:
            raise TypeError()


class Assessment(models.Model):
    title = models.CharField(
        max_length=50,
        null=True
    )

    course = models.ForeignKey(
        Course,
        on_delete=models.CASCADE,
        null=True,
    )

    level = models.SmallIntegerField(
        default=1
    )

    def next_assessment(self):

        if self.course.lesson.number == 0:
            return Assessment.objects.get(pk=2)
        else:
            temp = list(Assessment.objects.filter(level=1, course__gt=self.course).exclude(course__lesson__number=0))
            temp.sort()

        try:
            return temp[0]
        except IndexError:
            return Assessment.complete_level_one_assessment()

    @staticmethod
    def complete_level_one_assessment():

        return Assessment.objects.get(pk=11)

    def __str__(self):
        if self.course.lesson.number == 100:
            return "%s" % self.title

        return "%d.%d %s" % (self.course.lesson.number, self.course.chapter, self.title)

    def __gt__(self, other):
        if isinstance(other, Assessment):
            if self.course == other.course:
                return self.level > other.level
            else:
                return self.course > other.course
        else:
            raise TypeError("Assessment can't compare with other type")

    def __ge__(self, other):

        return self > other or self == other


class AssessmentCode(models.Model):
    code = models.TextField(
        max_length=1500,
        null=True
    )

    user = models.ForeignKey(
        'account.User',
        on_delete=models.CASCADE,
        null=True,
    )

    ass = models.ForeignKey(
        'Assessment',
        on_delete=models.CASCADE,
        null=True,
    )

    # 投票數
    point = models.IntegerField(
        default=0
    )

    datetime = models.DateTimeField(
        auto_now_add=True,
        null=True
    )

    def __str__(self):
        return "%s的%s" % (str(self.user), str(self.ass))

    def __gt__(self, other):
        if isinstance(other, AssessmentCode):

            return self.ass > other.ass

        else:
            raise TypeError()

    class Meta:
        unique_together = ('ass', 'user')


class HaveVoted(models.Model):
    user = models.ForeignKey(
        'account.User',
        on_delete=models.CASCADE,
        null=True
    )

    ass_code = models.ForeignKey(
        'AssessmentCode',
        on_delete=models.CASCADE,
        null=True
    )

    def __str__(self):
        return "%s在%s投給%s" % (str(self.user), str(self.ass_code.ass), str(self.ass_code.user))


class Comment(models.Model):
    date = models.DateTimeField(
        auto_now_add=True
    )

    content = models.TextField(
        default=""
    )

    like = models.PositiveIntegerField(
        default=0
    )

    dislike = models.PositiveIntegerField(
        default=0
    )

    user = models.ForeignKey(
        'account.User',
        on_delete=models.CASCADE,
        null=True
    )

    ass_code = models.ForeignKey(
        'AssessmentCode',
        on_delete=models.CASCADE,
        null=True
    )

    reply = models.ForeignKey(
        'Comment',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )

    def __str__(self):
        return "%s comment in %s" % (str(self.user), str(self.ass_code))

    def save(self, *args, **kwargs):
        if not self.reply:
            self.reply = None

        super(Comment, self).save(*args, **kwargs)


class HaveLike(models.Model):
    is_like = models.BooleanField()

    user = models.ForeignKey(
        'account.User',
        on_delete=models.CASCADE,
        null=True
    )

    comment = models.ForeignKey(
        'Comment',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )

# class HaveVoted(models.Model):
#     user = models.ForeignKey(
#         'account.User',
#         on_delete=models.CASCADE,
#         null=True
#     )
#
#     ass = models.ForeignKey(
#         'Assessment',
#         on_delete=models.CASCADE,
#         null=True
#     )
#
#     ass_code = models.ForeignKey(
#         'AssessmentCode',
#         on_delete=models.CASCADE,
#         null=True
#     )
#
#     def __str__(self):
#         return "%s在%s投給%s" % (str(self.user), str(self.ass_code.ass), str(self.ass_code.user))

assessment/views.py
from django.shortcuts import render
from django.contrib import messages
from django.http import JsonResponse, Http404
from django.template import loader
from django.contrib.auth.decorators import login_required

from EasyCoding.apps import assessment_list
from course.models import Lesson
from .check import function_data, check_user_code, usercode_handler
from .models import Assessment, AssessmentCode, HaveVoted, Comment, HaveLike, Content
from .apps import execute_sql, update_assess_code, get_vote_content_by_id, CommentContent, list_split

import os
import signal
import sys
from traceback import extract_tb
from random import randint


# Create your views here.
@login_required
def assessment(request, pk=-1):
    if pk == -1:
        pk = request.user.assess_progress.id
    if pk == 11:
        sql = """
            select id
            from assessment_assessment
            where id not in (
                        select a.id
                        from assessment_assessment as a,
                             assessment_assessmentcode as ac
                        where ac.user_id = 6
                          and ac.ass_id = a.id);
        """

        have_not_complete_assessment = execute_sql(sql)

        if have_not_complete_assessment:
            temp = randint(0, len(have_not_complete_assessment) - 1)
            pk = have_not_complete_assessment[temp][0]
        else:
            pk = 20  # TODO knacpack ppp

    template = 'assessment/assessment.html'

    data = function_data[pk]
    path = 'assessment/code/' + request.user.username
    user_file = path + '/' + str(data) + '.py'

    choice_assessment = Assessment.objects.get(pk=pk)

    # GET
    if request.method == 'GET':

        code = ''

        # 如果路徑上有檔案則輸入至code，否則輸入預設
        if os.path.isfile(user_file):
            with open(user_file, 'r') as f:
                temp = f.readlines()

                for i in temp:
                    code += i
        else:
            code = "def %s%s:" % (data.function_name, data.function_input)

        all_content = Content.objects.filter(assessment_id=pk)

        return render(request, template,
                      {'ass': choice_assessment,
                       'all_content': all_content,
                       'org_code': "def %s%s:" % (data.function_name, data.function_input),
                       'code': code,
                       'user': request.user.nickName,
                       'pk': pk})

    # POST

    code = request.POST.get('code')

    # 如果沒有code就罵他
    if not code:
        messages.error(request, "打code進來啦")
        return render(request, template)

    if function_data[pk].function_name not in code:
        output = "請不要亂改函式名稱"

        response = JsonResponse({'output': output, "is_answer_right": False}, safe=False)
        return response

    # 如果沒有資料夾就創一個
    if not os.path.isdir(path):
        os.mkdir(path)

    with open(user_file, 'w') as f:
        f.write(code)

    signal.signal(signal.SIGALRM, usercode_handler)
    signal.alarm(5)
    print(code)

    is_answer_right = False

    try:
        is_answer_right, output = check_user_code(pk, code)
    except SyntaxError as e:
        exc_type, exc_value, exc_tb = sys.exc_info()
        line_number = exc_value.lineno

        output = "在第%d行發生語法錯誤" % line_number

    except BaseException as e:
        print(e)
        is_answer_right = False
        exc_type, exc_value, exc_tb = sys.exc_info()
        print(extract_tb(exc_tb))
        temp = extract_tb(exc_tb)[-1]
        output = "在第%d行發生錯誤：\n%s" % (temp.lineno, str(exc_value))

    if "submit" in request.POST and is_answer_right:
        update_assess_code(request.user.id, pk, code)

        course_for_assessment = choice_assessment.course

        if course_for_assessment >= request.user.course_progress:
            request.user.course_progress = course_for_assessment.next_course()

        if choice_assessment >= request.user.assess_progress:
            request.user.assess_progress = request.user.assess_progress.next_assessment()

        request.user.save()

    response = JsonResponse({'output': output, "is_answer_right": is_answer_right}, safe=False)
    return response


@login_required
def vote(request, pk, sort_by="vote_number", page=1):
    template = "assessment/vote.html"
    user = request.user

    if request.method == "GET":
        ass = Assessment.objects.get(pk=pk)

        contents = get_vote_content_by_id(pk, request.user.id)

        sort_types = {
            "vote_number": "票數較多",
            "date_first": "由新至舊",
            "date_last": "由舊至新"
        }

        if sort_by == "vote_number":
            contents = sorted(contents, key=lambda x: x.point_percent, reverse=True)
        elif sort_by == "date_first":
            contents = sorted(contents, key=lambda x: x.datetime, reverse=True)
        elif sort_by == "date_last":
            contents = sorted(contents, key=lambda x: x.datetime)

        contents = list_split(contents, 4)
        page_number = len(contents)

        sql = """
            select ass_code_id
            from assessment_havevoted as hv, assessment_assessmentcode as ac
            where hv.user_id = %d and ac.ass_id = %d and hv.ass_code_id = ac.id    
        """ % (request.user.id, pk)

        already_voted = execute_sql(sql)
        already_voted = already_voted[0][0] if already_voted else None

        return render(request, template,
                      {"assessment": ass,
                       "contents": contents[page - 1],
                       "pk": pk,
                       "already_voted_id": already_voted,
                       "sort_by": sort_by,
                       "sort_types": sort_types.items(),
                       "page": page,
                       "page_number": page_number,
                       })

    # POST

    post_type = request.POST['type']

    if post_type == 'like':

        comment_id = request.POST['id']

        sql = """
            select is_like, id
            from assessment_havelike
            where user_id = %d and comment_id = %s
        """ % (request.user.id, comment_id)

        last_like = execute_sql(sql)
        comment = Comment.objects.get(pk=comment_id)

        if not last_like:
            comment.like += 1
            comment.save()

            HaveLike.objects.create(
                is_like=True,
                user_id=request.user.id,
                comment_id=comment_id
            )

            status = 'create'

        elif last_like[0][0]:
            comment.like -= 1
            comment.save()

            temp = HaveLike.objects.get(pk=last_like[0][1])
            temp.delete()

            status = 'delete'

        else:
            comment.like += 1
            comment.dislike -= 1
            comment.save()

            temp = HaveLike.objects.get(pk=last_like[0][1])
            temp.is_like = True
            temp.save()

            status = 'change'

        response = JsonResponse({"status": status, "like": comment.like, "dislike": comment.dislike})

    elif post_type == 'dislike':

        comment_id = request.POST['id']

        sql = """
            select is_like, id
            from assessment_havelike
            where user_id = %d and comment_id = %s
        """ % (request.user.id, comment_id)

        last_like = execute_sql(sql)
        comment = Comment.objects.get(pk=comment_id)

        if not last_like:
            comment.dislike += 1
            comment.save()

            HaveLike.objects.create(
                is_like=False,
                user_id=request.user.id,
                comment_id=comment_id
            )

            status = "create"

        elif last_like[0][0]:
            comment.dislike += 1
            comment.like -= 1
            comment.save()

            temp = HaveLike.objects.get(pk=last_like[0][1])
            temp.is_like = False
            temp.save()

            status = "change"

        else:
            comment.dislike -= 1
            comment.save()

            temp = HaveLike.objects.get(pk=last_like[0][1])
            temp.delete()

            status = "delete"

        response = JsonResponse({"status": status, "like": comment.like, "dislike": comment.dislike})

    elif post_type == "comment":

        ass_code_id = int(request.POST.get("ac_id"))
        reply_id = request.POST.get("reply")
        reply_id = int(reply_id) if reply_id != "None" else None
        content = request.POST.get("content")

        return_comment = Comment.objects.create(
            content=content,
            user_id=request.user.id,
            ass_code_id=ass_code_id,
            reply_id=reply_id
        )

        if reply_id:

            t = loader.get_template('assessment/vote-comment-reply.html')

            b = CommentContent(return_comment, read_user_id=request.user.id)

            c = t.render({
                'user': request.user,
                'replied': b
            })

        else:

            t = loader.get_template('assessment/vote-comment.html')

            b = CommentContent(return_comment, read_user_id=request.user.id)

            c = t.render({
                'content': {"id": ass_code_id},
                'user': request.user,
                'main_comment': b
            })

        response = JsonResponse({"new_comment": c})

    elif post_type == "vote":
        org_point = -1
        org_id = 0

        ass_code_id = int(request.POST.get("id"))
        ass_id = pk

        have_vote_this_ass_code = HaveVoted.objects.filter(user_id=user.id, ass_code_id=ass_code_id)

        if have_vote_this_ass_code:

            HaveVoted.objects.get(pk=have_vote_this_ass_code[0].pk).delete()
            ass_code = AssessmentCode.objects.get(pk=ass_code_id)
            ass_code.point -= 1
            ass_code.save()
            point = ass_code.point
            org_id = ass_code_id

        else:

templates/assessment/assessment.html
{% extends "base.html" %}

{% block title %}
    {{ ass }}
{% endblock %}

{% load static %}
{% load assessment_extras %}

{% block csslink %}
    <link rel="stylesheet" href="{% static "css/assessment/assessment.css" %}">
    <link rel="stylesheet" href="{% static "css/assessment/ed.css" %}">
    <link rel="stylesheet" href="{% static "css/course/caw.css" %}">
{% endblock %}

{% block jslink %}
    <script src="{% static "src-noconflict/ext-language_tools.js" %}"></script>
    <script src="{% static "src-noconflict/ace.js" %}"></script>
{% endblock %}

{% block content %}

    <!--contain start-->
    <div class="container-fluid" style="margin: 15px 0">
        <div id="tab1" class="row">
            <div id="assessment-wrapper" class="col-4">
                <span id="topic">1</span>
                <span id="output">2</span>
                <div id="tab">
                    <!-- 頁籤按鈕 -->
                    <ul>
                        <li>
                            <a href="#topic">
                                <h6>題目</h6>
                            </a>
                        </li>

                        <li>
                            <a href="#output">
                                <h6>輸出</h6>
                            </a>
                        </li>

                        <a id="a-vote" href="{% url "assessment:vote" pk %}">
                            <button type="button" id="btn-vote" class="btn btn-link">
                                投票
                            </button>
                        </a>
                    </ul>

                    <!-- 頁籤的內容區塊 -->
                    <div class="topic-content">
                        <div class="inner-container">
                            {# TODO need fix #}
                            <div class="content">
                                {% for content in all_content %}
                                    {% if content.isTitle %}
                                        <h5>
                                            {{ content.content }}
                                        </h5>
                                    {% elif content.isSubTitle %}
                                        <h6>
                                            {{ content.content }}
                                        </h6>
                                    {% elif content.isText %}
                                        <p class="word">
                                            {{ content.content }}
                                        </p>
                                    {% elif content.isCode %}
                                        <pre class="part">{{ content.content|safe }}</pre>
                                    {% elif content.isImage %}
                                        <img src="{% static content.content %}">
                                    {% elif content.isLink %}
                                        <p class="wikilink">{{ content.content|safe }}</p>
                                    {% elif content.isTable %}
                                        <table class="tab">
                                            {{ content.content|safe }}
                                        </table>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    </div>

                    <div class="output-content">
                        <div class="inner-container">
                            <div class="content">
                                <div id="exe-output" style="padding: 10px 0px">
                                    <div class="none">
                                        <p>這裡什麼都還沒有 <br>快來執行吧!(ゝ∀･)</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <button type="button" id="btn-run" class="btn btn-outline-dark">執行</button>
                    <button type="button" id="btn-sendout" class="btn btn-outline-dark">送出</button>

                </div>
            </div>

            {# @formatter:off #}
            <div id="code-wrapper" class="col-8"><div id="editor"><div id="editorDiv">{{ org_code }}</div></div></div>
            {# @formatter:on #}
        </div>

    </div>
    <!--contain end-->
{% endblock %}

{% block tailjslink %}
    {% csrf_token %}
    <script>$.ajaxSetup({headers: {"X-CSRFToken": '{{ csrf_token }}'}});</script>

    <script>
        ace.require("ace/ext/language_tools");
        //建立輸入框
        let editor = ace.edit("editor");
        //輸入代碼提示
        editor.setOptions({
            enableBasicAutocompletion: true,
            enableSnippets: true,
            enableLiveAutocompletion: true
        });
        editor.setFontSize(20);
        //選擇語言
        editor.getSession().setMode("ace/mode/python");
        //设置初始内容
        editor.setValue(`{{ code|backslash|safe }}`);

        editor.setTheme("ace/theme/ihatewhite");

        editor.on('change', function () {
            $("#btn-sendout").hide();

            $("#btn-vote").hide();
        });

        {#execute#}
        var a;
        $("#btn-run").click(function () {
            {#TODO runtime display#}
            $("#tab > ul > li:nth-child(2) > a")[0].click();

            let code = editor.getValue();

            $.ajax({
                type: "POST",
                data: {code: code},
                url: "{% url 'assessment:assessment' pk %}",
                cache: false,
                dataType: "json",
                success: function (result) {
                    console.log(result);

                    if (result.is_answer_right) {
                        $("#btn-sendout").show();

                        $("#btn-vote").show();
                    } else {
                        $("#btn-sendout").hide();

                        $("#btn-vote").hide();
                    }

                    let exe_output = $("#exe-output");
                    let output = result.output;

                    exe_output.html("");
                    a = output;

                    if (typeof(output) === "string") {
                        exe_output.html(output);
                    } else {
                        output.forEach(function (e) {
                            let wrapper = $("<div>");

                            if (e["is_answer_right"]) {
                                wrapper.addClass("correct");

                                let answer_right = $("<green>").text("正確");
                                let temp = $("<div>");

                                temp.append(answer_right);
                                wrapper.append(temp);
                            } else {
                                wrapper.addClass("wrong");

                                let answer_right = $("<red>").text("錯誤");
                                let temp = $("<div>");

                                temp.append(answer_right);
                                wrapper.append(temp);
                            }

                            let temp = $("<div>").text("輸入:");
                            let input = $("<pre>").text(e["input"]);

                            temp.append(input);
                            wrapper.append(temp);

                            temp = $("<div>").text("輸出:");
                            let output = $("<pre>").html(e["output"]);

                            temp.append(output);
                            wrapper.append(temp);

                            if (!e["is_answer_right"]) {
                                let realans = $("<div>").addClass("realans");
                                temp = $("<div>");
                                let green = $("<green>").text("正確輸出:");
                                let answer = $("<pre>").html(e["answer"]);

                                realans.append(temp);
                                temp.append(green);
                                green.append(answer);
                                wrapper.append(realans);
                            }

                            wrapper.appendTo(exe_output);
                        });

                    }

                },
                error: function () {
                    alert("執行時間過久");
                }
            });
        });

        {#submit#}
        $("#btn-sendout").click(function () {
            let code = editor.getValue();

            $.ajax({
                type: "POST",
                data: {code: code, submit: "submit"},
                url: "{% url 'assessment:assessment' pk %}",
                cache: false,
                dataType: "json",
                success: function (result) {
                    $("#btn-vote").show();

                    alert("成功送出");

                    window.location.href = "{% url "assessment:vote" pk %}"
                },
                error: function () {
                    console.log(888);
                }
            });

        });

        /*bububu*/
    </script>
{% endblock %}

templates/assessment/vote-comment-reply.html
{% load static %}
{% load tz %}


<div class="row no-gutters">

    <div class="" style="margin: 10px;">
        <div class="comment">
            <img src="{% static replied.user.image_url %}"
                 alt=""
                 style="width: 35px">
        </div>
    </div>

    <div class="col" style="padding-top: 10px;">
        <div class="row no-gutters">
            <p class="form-control align-middle">{{ replied.content }}</p>
        </div>

        <div class="row no-gutters comment-feature">
            <div class="like">
                {% if replied.like_status %}
                    <a class="liked"
                       href="javascript: void(0)"
                       data-comment-id="{{ replied.id }}"
                       data-type="like">
                        <i class="far fa-thumbs-up"></i>
                    </a>
                {% else %}
                    <a href="javascript: void(0)"
                       data-comment-id="{{ replied.id }}"
                       data-type="like">
                        <i class="far fa-thumbs-up"></i>
                    </a>
                {% endif %}

                <span class="like-number">
                    {{ replied.like }}
                </span>

                {% if replied.like_status == False %}
                    <a class="liked"
                       href="javascript: void(0)"
                       data-comment-id="{{ replied.id }}"
                       data-type="dislike">
                        <i class="far fa-thumbs-down"></i>
                    </a>
                {% else %}
                    <a href="javascript: void(0)"
                       data-comment-id="{{ replied.id }}"
                       data-type="dislike">
                        <i class="far fa-thumbs-down"></i>
                    </a>
                {% endif %}

                <span class="dislike-number">
                    {{ replied.dislike }}
                </span>
            </div>

            <div class="">
                <p>{{ replied.datetime|timezone:"Asia/Taipei"|date:"Y-m-d a h.i.s" }}</p>
            </div>

            {% if replied.user == user %}
                <div>
                    <a class="comment-delete" href="javascript: void(0)" data-comment-id="{{ replied.id }}"
                       data-type="delete">
                        <i class="fas fa-trash-alt"></i>
                    </a>
                </div>
            {% endif %}
        </div>
    </div>

</div>