EasyCoding/urls.py
from django.contrib import admin
from django.urls import path, include
import django.contrib.auth.views as auth_view

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls'), name='account'),
    path('', views.home, name='home'),
    path('assessment/', include('assessment.urls'), name='assessment'),
    path('course/', include('course.urls'), name='course'),
    path('wiki/', include('wiki.urls'), name='wiki'),
    path('tutorial/', include('tutorial.urls'), name='tutorial'),
]

assessment/urls.py
from django.urls import path, include
from . import views

app_name = 'assessment'

urlpatterns = [
    path('', views.assessment, name="assessment_for_precess"),
    path('<int:pk>', views.assessment, name="assessment"),
    path('vote/<int:pk>', views.vote, name="vote"),
    path('vote/<int:pk>/<str:sort_by>', views.vote, name="vote"),
    path('vote/<int:pk>/<str:sort_by>/<int:page>', views.vote, name="vote"),
    path('assessment_add/<int:pk>', views.assessment_add, name="assessment_add"),
]

course/urls.py
from django.urls import path, include
from . import views

app_name = 'course'

urlpatterns = [
    path('', views.course, name="course_for_process"),
    path('<int:lesson_number>/<int:chapter>', views.course, name="course"),
    path('course_add/<int:lesson_number>/<int:chapter>', views.course_add, name="course_add")
]

tutorial/urls.py
from django.urls import path, include
from . import views

app_name = 'tutorial'

urlpatterns = [
    path('', views.home, name="home"),
    path('course/<int:lesson_number>/<int:chapter>', views.course, name="course"),
    path('assessment/<int:pk>', views.assessment, name="assessment"),
    path('vote/<int:pk>/<str:sort_by>/<int:page>', views.vote, name="vote"),
]

wiki/urls.py
from django.urls import path, include
from . import views

app_name = 'wiki'

urlpatterns = [
    path('<int:lesson>/<int:chapter>', views.wiki, name="wiki"),
]

tutorial/models.py
from django.db import models

# Create your models here.

assessment/views.py
from django.shortcuts import render
from django.contrib import messages
from django.http import JsonResponse, Http404
from django.template import loader
from django.contrib.auth.decorators import login_required

from EasyCoding.apps import assessment_list
from course.models import Lesson
from .check import function_data, check_user_code, usercode_handler
from .models import Assessment, AssessmentCode, HaveVoted, Comment, HaveLike, Content
from .apps import execute_sql, update_assess_code, get_vote_content_by_id, CommentContent, list_split

import os
import signal
import sys
from traceback import extract_tb
from random import randint


# Create your views here.
@login_required
def assessment(request, pk=-1):
    if pk == -1:
        pk = request.user.assess_progress.id
    if pk == 11:
        sql = """
            select id
            from assessment_assessment
            where id not in (
                        select a.id
                        from assessment_assessment as a,
                             assessment_assessmentcode as ac
                        where ac.user_id = 6
                          and ac.ass_id = a.id);
        """

        have_not_complete_assessment = execute_sql(sql)

        if have_not_complete_assessment:
            temp = randint(0, len(have_not_complete_assessment) - 1)
            pk = have_not_complete_assessment[temp][0]
        else:
            pk = 20  # TODO knacpack ppp

    template = 'assessment/assessment.html'

    data = function_data[pk]
    path = 'assessment/code/' + request.user.username
    user_file = path + '/' + str(data) + '.py'

    choice_assessment = Assessment.objects.get(pk=pk)

    # GET
    if request.method == 'GET':

        code = ''

        # 如果路徑上有檔案則輸入至code，否則輸入預設
        if os.path.isfile(user_file):
            with open(user_file, 'r') as f:
                temp = f.readlines()

                for i in temp:
                    code += i
        else:
            code = "def %s%s:" % (data.function_name, data.function_input)

        all_content = Content.objects.filter(assessment_id=pk)

        return render(request, template,
                      {'ass': choice_assessment,
                       'all_content': all_content,
                       'org_code': "def %s%s:" % (data.function_name, data.function_input),
                       'code': code,
                       'user': request.user.nickName,
                       'pk': pk})

    # POST

    code = request.POST.get('code')

    # 如果沒有code就罵他
    if not code:
        messages.error(request, "打code進來啦")
        return render(request, template)

    if function_data[pk].function_name not in code:
        output = "請不要亂改函式名稱"

        response = JsonResponse({'output': output, "is_answer_right": False}, safe=False)
        return response

    # 如果沒有資料夾就創一個
    if not os.path.isdir(path):
        os.mkdir(path)

    with open(user_file, 'w') as f:
        f.write(code)

    signal.signal(signal.SIGALRM, usercode_handler)
    signal.alarm(5)
    print(code)

    is_answer_right = False

    try:
        is_answer_right, output = check_user_code(pk, code)
    except SyntaxError as e:
        exc_type, exc_value, exc_tb = sys.exc_info()
        line_number = exc_value.lineno

        output = "在第%d行發生語法錯誤" % line_number

    except BaseException as e:
        print(e)
        is_answer_right = False
        exc_type, exc_value, exc_tb = sys.exc_info()
        print(extract_tb(exc_tb))
        temp = extract_tb(exc_tb)[-1]
        output = "在第%d行發生錯誤：\n%s" % (temp.lineno, str(exc_value))

    if "submit" in request.POST and is_answer_right:
        update_assess_code(request.user.id, pk, code)

        course_for_assessment = choice_assessment.course

        if course_for_assessment >= request.user.course_progress:
            request.user.course_progress = course_for_assessment.next_course()

        if choice_assessment >= request.user.assess_progress:
            request.user.assess_progress = request.user.assess_progress.next_assessment()

        request.user.save()

    response = JsonResponse({'output': output, "is_answer_right": is_answer_right}, safe=False)
    return response


@login_required
def vote(request, pk, sort_by="vote_number", page=1):
    template = "assessment/vote.html"
    user = request.user

    if request.method == "GET":
        ass = Assessment.objects.get(pk=pk)

        contents = get_vote_content_by_id(pk, request.user.id)

        sort_types = {
            "vote_number": "票數較多",
            "date_first": "由新至舊",
            "date_last": "由舊至新"
        }

        if sort_by == "vote_number":
            contents = sorted(contents, key=lambda x: x.point_percent, reverse=True)
        elif sort_by == "date_first":
            contents = sorted(contents, key=lambda x: x.datetime, reverse=True)
        elif sort_by == "date_last":
            contents = sorted(contents, key=lambda x: x.datetime)

        contents = list_split(contents, 4)
        page_number = len(contents)

        sql = """
            select ass_code_id
            from assessment_havevoted as hv, assessment_assessmentcode as ac
            where hv.user_id = %d and ac.ass_id = %d and hv.ass_code_id = ac.id    
        """ % (request.user.id, pk)

        already_voted = execute_sql(sql)
        already_voted = already_voted[0][0] if already_voted else None

        return render(request, template,
                      {"assessment": ass,
                       "contents": contents[page - 1],
                       "pk": pk,
                       "already_voted_id": already_voted,
                       "sort_by": sort_by,
                       "sort_types": sort_types.items(),
                       "page": page,
                       "page_number": page_number,
                       })

    # POST

    post_type = request.POST['type']

    if post_type == 'like':

        comment_id = request.POST['id']

        sql = """
            select is_like, id
            from assessment_havelike
            where user_id = %d and comment_id = %s
        """ % (request.user.id, comment_id)

        last_like = execute_sql(sql)
        comment = Comment.objects.get(pk=comment_id)

        if not last_like:
            comment.like += 1
            comment.save()

            HaveLike.objects.create(
                is_like=True,
                user_id=request.user.id,
                comment_id=comment_id
            )

            status = 'create'

        elif last_like[0][0]:
            comment.like -= 1
            comment.save()

            temp = HaveLike.objects.get(pk=last_like[0][1])
            temp.delete()

            status = 'delete'

        else:
            comment.like += 1
            comment.dislike -= 1
            comment.save()

            temp = HaveLike.objects.get(pk=last_like[0][1])
            temp.is_like = True
            temp.save()

            status = 'change'

        response = JsonResponse({"status": status, "like": comment.like, "dislike": comment.dislike})

    elif post_type == 'dislike':

        comment_id = request.POST['id']

        sql = """
            select is_like, id
            from assessment_havelike
            where user_id = %d and comment_id = %s
        """ % (request.user.id, comment_id)

        last_like = execute_sql(sql)
        comment = Comment.objects.get(pk=comment_id)

        if not last_like:
            comment.dislike += 1
            comment.save()

            HaveLike.objects.create(
                is_like=False,
                user_id=request.user.id,
                comment_id=comment_id
            )

            status = "create"

        elif last_like[0][0]:
            comment.dislike += 1
            comment.like -= 1
            comment.save()

            temp = HaveLike.objects.get(pk=last_like[0][1])
            temp.is_like = False
            temp.save()

            status = "change"

        else:
            comment.dislike -= 1
            comment.save()

            temp = HaveLike.objects.get(pk=last_like[0][1])
            temp.delete()

            status = "delete"

        response = JsonResponse({"status": status, "like": comment.like, "dislike": comment.dislike})

    elif post_type == "comment":

        ass_code_id = int(request.POST.get("ac_id"))
        reply_id = request.POST.get("reply")
        reply_id = int(reply_id) if reply_id != "None" else None
        content = request.POST.get("content")

        return_comment = Comment.objects.create(
            content=content,
            user_id=request.user.id,
            ass_code_id=ass_code_id,
            reply_id=reply_id
        )

        if reply_id:

            t = loader.get_template('assessment/vote-comment-reply.html')

            b = CommentContent(return_comment, read_user_id=request.user.id)

            c = t.render({
                'user': request.user,
                'replied': b
            })

        else:

            t = loader.get_template('assessment/vote-comment.html')

            b = CommentContent(return_comment, read_user_id=request.user.id)

            c = t.render({
                'content': {"id": ass_code_id},
                'user': request.user,
                'main_comment': b
            })

        response = JsonResponse({"new_comment": c})

    elif post_type == "vote":
        org_point = -1
        org_id = 0

        ass_code_id = int(request.POST.get("id"))
        ass_id = pk

        have_vote_this_ass_code = HaveVoted.objects.filter(user_id=user.id, ass_code_id=ass_code_id)

        if have_vote_this_ass_code:

            HaveVoted.objects.get(pk=have_vote_this_ass_code[0].pk).delete()
            ass_code = AssessmentCode.objects.get(pk=ass_code_id)
            ass_code.point -= 1
            ass_code.save()
            point = ass_code.point
            org_id = ass_code_id

        else:

course/views.py
from django.shortcuts import render
from django.http.response import JsonResponse
from django.http import Http404
from django.contrib.auth.decorators import login_required

from .apps import CourseMenuContent, CourseAdmin, FillQuestion, compare_str
from .models import Course, Content, Fill_Answer, Lesson


# Create your views here.
@login_required
def course(request, lesson_number=-1, chapter=-1):
    user_course = request.user.course_progress

    if lesson_number == -1 and chapter == -1:
        lesson_number, chapter = user_course.lesson.number, user_course.chapter

    try:
        choice_course = Course.objects.get(lesson=lesson_number, chapter=chapter)
    except Course.DoesNotExist:
        if lesson_number < Lesson.get_lesson_length():
            chapter = 1
            lesson_number += 1
            choice_course = Course.objects.get(lesson=lesson_number, chapter=chapter)
        else:
            raise Http404("之後就沒囉!!")

    assessment_pk = False
    assessment_for_choice_course = choice_course.assessment_set.all().filter(level=1)

    if assessment_for_choice_course:
        assessment_pk = assessment_for_choice_course[0].pk

    if request.user.is_superuser:
        pass
    elif lesson_number > user_course.lesson.number:
        raise Http404("YOU SHALL NOT PASS!!!!")
    elif lesson_number == user_course.lesson.number:
        if chapter > user_course.chapter:
            raise Http404("YOU SHALL NOT PASS!!!!")

    if request.method == "GET":
        template = "course/course.html"

        all_content = list(Content.objects.filter(course=choice_course))
        all_content.sort()

        all_course_menu = []

        for i in Lesson.objects.all().exclude(number__gt=10).exclude(number__lt=1):
            all_course_menu.append(
                CourseMenuContent(i, user_course)
            )

        fill_question = FillQuestion(choice_course)

        return render(request, template, {"all_content": all_content,
                                          "course_name": str(choice_course),
                                          "all_course_menu": all_course_menu,
                                          "lesson": lesson_number,
                                          "chapter": chapter,
                                          "fill_question": fill_question,
                                          "assessment_pk": assessment_pk})

    user_answer = request.POST["answer"]
    fill_answers = Fill_Answer.objects.filter(fill__course=choice_course)

    is_answer_right = False
    which_false = [i for i in range(100)]

    for answer in fill_answers:

        is_answer_right, temp_which_false = compare_str(user_answer, answer.answer)

        if len(temp_which_false) < len(which_false):
            which_false = temp_which_false

        if is_answer_right:
            break

    is_assessment_exist = bool(assessment_pk)

    if is_answer_right:

        if choice_course == user_course and not is_assessment_exist:
            request.user.course_progress = choice_course.next_course()
            request.user.save()

    return JsonResponse({"is_answer_right": is_answer_right,
                         "which_false": which_false,
                         "is_assessment_exist": is_assessment_exist})


@login_required
def course_add(request, lesson_number=1, chapter=1):
    if not request.user.is_superuser:
        raise Http404("not exist")

    template = "course/seven.html"
    choice_course = Course.objects.get(lesson__number=lesson_number, chapter=chapter)

    if request.method == "GET":

        all_content = list(Content.objects.filter(course=choice_course))
        all_content.sort()

        all_course = []

        for i in Lesson.objects.all():
            all_course.append(
                CourseAdmin(i)
            )

        return render(request, template, {
            "all_content": all_content,
            "all_course": all_course,
            "lesson": lesson_number,
            "chapter": chapter
        })

    # data = request.POST.get("data[0][]")
    datas = dict(request.POST)
    number = int(datas["number"][0])
    size = len(choice_course.content_set.all())

    count = number if number > size else size

    for i in range(count):
        if i < number:
            data = datas["data[%d][]" % i]

            data_type = data[1]
            value = data[2]
        else:
            temp = Content.objects.get(course=choice_course, number=i)
            temp.delete()

            continue

        temp = Content.objects.get_or_create(course=choice_course, number=i)[0]

        temp.reset_type()

        if data_type == "text":
            temp.isText = True
        elif data_type == "code":
            temp.isCode = True
        elif data_type == "title":
            temp.isTitle = True
        elif data_type == "subtitle":
            temp.isSubTitle = True
        elif data_type == "image":
            temp.isImage = True
            if '/' in value:
                temp.content = value
            else:
                temp.content = "course_image/%d%d/%s" % (lesson_number, chapter, value)
            temp.save()
            continue

        temp.content = value

        temp.save()

    return JsonResponse({})

templates/tutorial/assessment.html
{% extends "assessment/assessment.html" %}

{% load assessment_extras %}

{% block tutorial %}
    {% include "tutorial/tutorial.html" %}
{% endblock %}

{% block tutorialjs %}
    <script>
        let sub_tittle_content = $("#sub-tittle > span");

        let next_step = $("#next-step");

        let step = 0;
        let script = [
            "右邊這個區塊是給你輸入程式碼的地方",
            "左邊這個區塊是顯示題目與輸出結果的地方",
            "現在你可以開始按照題目需求開始輸入程式了，輸入好後就可以按下執行來執行程式囉",
        ];

        $("#menu a").click(function () {
            $(this).attr('href', "javascript:void(0)");
            alert("教學完再點啦");
        });

        sub_tittle_content.text(script[step]);
        $("#code-wrapper").css("z-index", 1002);

        next_step.click(function (e) {
            if (step < script.length) {
                step += 1;
            }

            sub_tittle_content.text(script[step]);

            if (step === 1) {
                $("#assessment-wrapper").css("z-index", 1002);
                $("#code-wrapper").css("z-index", 1000);
            } else if (step === 2) {
                next_step.hide();
                $("#code-wrapper").css("z-index", 1002);
            } else {
                next_step.show();
            }
        });

        $("#a-vote").attr("href", "{% url "tutorial:vote" 12 "date_first" 1 %}")
    </script>
{% endblock %}

{% block tailjslink %}
    {% csrf_token %}
    <script>$.ajaxSetup({headers: {"X-CSRFToken": '{{ csrf_token }}'}});</script>

    <script>
        ace.require("ace/ext/language_tools");
        //建立輸入框
        let editor = ace.edit("editor");
        //輸入代碼提示
        editor.setOptions({
            enableBasicAutocompletion: true,
            enableSnippets: true,
            enableLiveAutocompletion: true
        });
        editor.setFontSize(20);
        //選擇語言
        editor.getSession().setMode("ace/mode/python");
        //设置初始内容
        editor.setValue(`{{ code|backslash|safe }}`);

        editor.setTheme("ace/theme/ihatewhite");

        editor.on('change', function () {
            $("#btn-sendout").hide();

            $("#btn-vote").hide();
        });

        {#execute#}
        var a;
        $("#btn-run").click(function () {
            $("#tab > ul > li:nth-child(2) > a")[0].click();

            let code = editor.getValue();

            $.ajax({
                type: "POST",
                data: {code: code},
                url: "{% url 'assessment:assessment' pk %}",
                cache: false,
                dataType: "json",
                success: function (result) {

                    if (result.is_answer_right) {
                        $("#btn-sendout").show();

                        sub_tittle_content.text("答對後請按下送出按鍵把程式碼正式繳交");
                    } else {
                        $("#btn-sendout").hide();

                        $("#btn-vote").hide();
                    }

                    let exe_output = $("#exe-output");
                    let output = result.output;

                    exe_output.html("");
                    a = output;

                    if (typeof(output) === "string") {
                        exe_output.html(output);
                    } else {
                        output.forEach(function (e) {
                            let wrapper = $("<div>");

                            if (e["is_answer_right"]) {
                                wrapper.addClass("correct");

                                let answer_right = $("<green>").text("正確");
                                let temp = $("<div>");

                                temp.append(answer_right);
                                wrapper.append(temp);
                            } else {
                                wrapper.addClass("wrong");

                                let answer_right = $("<red>").text("錯誤");
                                let temp = $("<div>");

                                temp.append(answer_right);
                                wrapper.append(temp);
                            }

                            let temp = $("<div>").text("輸入:");
                            let input = $("<div>").text(e["input"]);

                            temp.append(input);
                            wrapper.append(temp);

                            temp = $("<div>").text("輸出:");
                            let output = $("<pre>").html(e["output"]);

                            temp.append(output);
                            wrapper.append(temp);

                            if (!e["is_answer_right"]) {
                                let realans = $("<div>").addClass("realans");
                                temp = $("<div>");
                                let green = $("<green>").text("正確輸出:");
                                let answer = $("<pre>").html(e["answer"]);

                                realans.append(temp);
                                temp.append(green);
                                green.append(answer);
                                wrapper.append(realans);
                            }

                            wrapper.appendTo(exe_output);
                        });

                    }

                },
                error: function () {
                    alert(888);
                }
            });
        });

        {#submit#}
        $("#btn-sendout").click(function () {
            let code = editor.getValue();

            $.ajax({
                type: "POST",
                data: {code: code, submit: "submit"},
                url: "{% url 'assessment:assessment' pk %}",
                cache: false,
                dataType: "json",
                success: function (result) {
                    $("#btn-vote").show();

                    alert("成功送出");

                    sub_tittle_content.text("成功送出後就可以點擊前往投票頁面觀看其他人的程式碼");

                    window.location.href = "{% url "tutorial:vote" pk "date_first" 1 %}"
                },
                error: function () {
                    console.log(888);
                }
            });

        });
    </script>
{% endblock %}

templates/tutorial/course.html
{% extends "course/course.html" %}

{% block tutorial %}
    {% include "tutorial/tutorial.html" %}
{% endblock %}

{% block tutorialjs %}
    <script>
        let sub_tittle_content = $("#sub-tittle > span");

        let next_step = $("#next-step");

        let step = 0;
        {% if chapter == 1 %}
            let script = [
                "第一課的內容是一步一步帶領你在電腦裡安裝python",
                "在看完課程內容後就可以到網頁最下方回答填充題進入下一課",
                "如果答案正確就可以點擊下一課繼續學習囉",
            ];
        {% else %}
            let script = [
                "第二課的內容是介紹python官方提供的打程式的地方",
                "在看完課程內容後就可以到網頁最下方回答填充題進入作業",
                "如果答案正確就可以點擊寫作業前往第一份作業囉"
            ];
        {% endif %}


        sub_tittle_content.text(script[step]);

        next_step.click(function (e) {
            if (step < script.length) {
                step += 1;
            }

            sub_tittle_content.text(script[step]);

            if (step === 1) {
                next_step.hide();
            } else {
                next_step.show();
            }
        });

        $("#menu a").click(function (e) {
            $(this).attr('href', "javascript:void(0)");
            alert("教學完再點啦");
        });

        $("#course-wrapper").css("z-index", 1002);

        let fill_question = $("#fill-question");
        let have_scroll = false;

        $(window).scroll(function () {
            if (!have_scroll) {

                let hT = fill_question.offset().top,
                    hH = fill_question.outerHeight(),
                    wH = $(window).height(),
                    wS = $(this).scrollTop();

                if (wS > (hT + hH - wH)) {

                    have_scroll = true;
                    $("#fill-question .code > input:first-child").focus();
                    sub_tittle_content.text("請將答案依序填入格子內，填完後便可按下送出鍵送出答案(記得切換輸入法)");
                    next_step.hide();
                }
            }
        });

        fill_answers_submit.click(function () {
            answer_send();
            step = 2;
            sub_tittle_content.text(script[step]);
        });

        $("#next-course").click(function () {
            window.location.href = "{% url "tutorial:course" lesson chapter|add:'1' %}"
        });

        {% if assessment_pk %}
            $("#goto-assessment").click(function () {
                window.location.href = "{% url "tutorial:assessment" assessment_pk %}"
            });
        {% endif %}
    </script>
{% endblock %}

templates/tutorial/home.html
{% extends "home.html" %}

{% block taildiv %}
    {% include "tutorial/tutorial.html" %}
{% endblock %}

{% block tailjs %}
    <script>
        let sub_tittle_content = $("#sub-tittle > span");
        let next_step = $("#next-step");

        let step = 0;

        let script = [
            "歡迎來到easycoding，請點擊下一步按鈕開始新手教學",
            "你現在在的地方是你的home，你可以從這裡開始學習課程、練習作業、查看個人檔案和去文件找資料",
            "第一步我們先來看看你學習課程的地方，請點擊課程內的「0.新手教學」",
        ];

        sub_tittle_content.text(script[step]);

        $("#menu a").click(function (e) {
            $(this).attr('href', "javascript:void(0)");
            alert("教學完再點啦");
        });

        $("#course-wrapper").css("z-index", 1002);

        next_step.click(function (e) {
            if (step < script.length) {
                step += 1;
            }

            sub_tittle_content.text(script[step]);

            if(step === 2){
                next_step.hide();
            }else{
                next_step.show();
            }
        });

        $(".todolist > ul > li:first-child > a").click(function () {
            sub_tittle_content.text("接著請點擊課程目錄中的『0-1 安裝Python的IDE』進入課程頁面");
        });
    </script>
{% endblock %}

templates/tutorial/tutorial.html
<div class="limit">
</div>

{# TODO skip button #}
<nav id="sub-tittle" class="navbar fixed-bottom">
    <span class="navbar-text">
    </span>

    <button id="next-step">
        下一步
        <i class="fas fa-chevron-down"></i>
    </button>
</nav>

templates/tutorial/vote.html
{% extends "assessment/vote.html" %}

{% block tutorial %}
    {% include "tutorial/tutorial.html" %}
{% endblock %}

{% block tutorialjs %}
    <script>
        let sub_tittle_content = $("#sub-tittle > span");

        let next_step = $("#next-step");

        let step = 0;
        let script = [
            "這裡是投票頁，你可以看到剛剛你寫完的作業就放在這裡",
            "在這裡你也可以看到其他人的程式碼並給你覺得最好的程式碼投票",
            "如果看不懂其他人的程式碼也可以在底下留言討論",
            "恭喜你完成新手教學，點一下右邊的回首頁就可以回到首頁囉"
        ];

        sub_tittle_content.text(script[step]);

        $(".order-type").click(function () {
            $(this).attr("href", "javascript:void(0)");
            alert("教學完再點啦");
        });

        $("#menu a").click(function (e) {
            $(this).attr('href', "javascript:void(0)");
            alert("教學完再點啦");
        });

        $(".page-link").click(function(){
            $(this).attr('href', "javascript:void(0)");
            alert("教學完再點啦");
        })

        $(".limit").css("z-index", -1);

        $("#assessment_back").attr("href", "{% url "tutorial:assessment" pk %}");

        next_step.click(function (e) {
            if (step < script.length) {
                step += 1;
            }

            sub_tittle_content.text(script[step]);

            if(step === 3){
                next_step.text("回首頁");
                next_step.click(function(){
                    window.location.href = "{% url "home" %}";
                })
            }
        });
    </script>
{% endblock %}