EasyCoding/urls.py
from django.contrib import admin
from django.urls import path, include
import django.contrib.auth.views as auth_view

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls'), name='account'),
    path('', views.home, name='home'),
    path('assessment/', include('assessment.urls'), name='assessment'),
    path('course/', include('course.urls'), name='course'),
    path('wiki/', include('wiki.urls'), name='wiki'),
    path('tutorial/', include('tutorial.urls'), name='tutorial'),
]

account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile/<username>', views.profile_for_other, name='profile_for_other'),
    path('achievement/', views.achievement, name='achievement'),
    path('achievement/<username>', views.achievement_for_other, name='achievement_for_other'),
    path('contact/', views.contact, name='contact')
]

assessment/urls.py
from django.urls import path, include
from . import views

app_name = 'assessment'

urlpatterns = [
    path('', views.assessment, name="assessment_for_precess"),
    path('<int:pk>', views.assessment, name="assessment"),
    path('vote/<int:pk>', views.vote, name="vote"),
    path('vote/<int:pk>/<str:sort_by>', views.vote, name="vote"),
    path('vote/<int:pk>/<str:sort_by>/<int:page>', views.vote, name="vote"),
    path('assessment_add/<int:pk>', views.assessment_add, name="assessment_add"),
]

course/urls.py
from django.urls import path, include
from . import views

app_name = 'course'

urlpatterns = [
    path('', views.course, name="course_for_process"),
    path('<int:lesson_number>/<int:chapter>', views.course, name="course"),
    path('course_add/<int:lesson_number>/<int:chapter>', views.course_add, name="course_add")
]

wiki/urls.py
from django.urls import path, include
from . import views

app_name = 'wiki'

urlpatterns = [
    path('<int:lesson>/<int:chapter>', views.wiki, name="wiki"),
]

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% load static %}
    <link rel="shortcut icon" href="{% static "img/favicon.ico" %}">

    <!--.css-->
    <link rel="stylesheet" href="{% static "boot/bootstrap-4.0.0.css" %}">
    <link rel="stylesheet" href="{% static "css/global/menu.css" %}">
    <link rel="stylesheet" href="{% static "css/global/tutorial.css" %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"
          integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    {% block csslink %}
    {% endblock %}

    <!--.js-->
    <script src="{% static "boot/jquery-3.2.1.min.js" %}"></script>
    <script src="{% static "boot/bootstrap-4.0.0.js" %}"></script>
    {% block jslink %}
    {% endblock %}
</head>

<body style="background-color: #eef5f9">
<!--menu-->
<nav id="menu" class="navbar navbar-expand-md sticky-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url "home" %}">
            <img src="{% static "img/bubu.png" %}" width="170px">
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#meun-collapse"
                style="margin-right: 15px">
            <div class="menu-toggle">
                <span class="menu-toggle-grippy"></span>
            </div>
        </button>

        <div class="collapse navbar-collapse" id="meun-collapse">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url "account:profile" %}">個人檔案</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url "course:course_for_process" %}">課程</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url "assessment:assessment_for_precess" %}">作業</a>
                </li>

{#                <li class="nav-item">#}
{#                    <a class="nav-link" href="{% url "account:contact" %}">聯繫</a>#}
{#                </li>#}

                <li class="nav-item">
                    <a class="nav-link" href="{% url "account:logout" %}">登出</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

{% block tutorial %}
{% endblock %}

<!--contain start-->
{% block content %}
{% endblock %}
<!--contain end-->

<!--footer-->
<footer class="container-fluid text-cener">
    <div class="row">
        <div class="col-lg-3 col-sm-2 col-1"></div>

        <div class="col-lg-4 col-sm-4 col-5">
            <h3>關於我們</h3><br>
            <h4>國立台中科技大學 資訊管理科</h4>
        </div>

        <div class="col-lg-2 col-sm-4 col-5">
            <img src="{% static "img/p.png" %}" class="icon" width=100>
        </div>
    </div>
</footer>

{#<script src="{% static 'js/menu.js' %}"></script>#}
{% block tailjslink %}
{% endblock %}

{% block tutorialjs %}

{% endblock %}

</body>

</html>

templates/index.html
<!DOCTYPE html>
<html>

{% load static %}

<head>
    <title>Easy Coding</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--no online-->
    <link rel="stylesheet" href="{% static "boot/bootstrap-4.0.0.css" %}">
    <link rel="stylesheet" href="{% static "css/global/menu.css" %}">
    {#    <link rel="stylesheet" href="{% static "css/index/index.css" %}">#}
    <link rel="stylesheet" href="{% static "css/index/style.css" %}">
    <link rel="stylesheet" href="{% static "css/global/fontawesome.css" %}">

    <!--no online-->
    <script src="{% static "boot/jquery-3.2.1.min.js" %}"></script>
    <script src="{% static "boot/bootstrap-4.0.0.js" %}"></script>

    <link rel="shortcut icon" href="{% static "img/favicon.ico" %}">
</head>

<body>

<!--menu-->
<nav id="menu" class="navbar navbar-expand-md sticky-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url "home" %}">
            <img src="{% static 'img/bubu.png' %}" width="170px">
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#meun-collapse"
                style="margin-right: 15px">
            <div class="menu-toggle">
                <span class="menu-toggle-grippy"></span>
            </div>
        </button>

        <div class="collapse navbar-collapse" id="meun-collapse">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url "account:login" %}">登入</a>
                </li>

{#                <li class="nav-item">#}
{#                    <a class="nav-link" href="{% url "account:contact" %}">聯繫我們</a>#}
{#                </li>#}
            </ul>
        </div>
    </div>
</nav>


<div id="home">
    <div class="landing-text">
        <h1>Easy Coding</h1>
        <h3>開始Python的旅程</h3>
        <a href="{% url "account:register" %}" class="btn btn-outline-dark btn-lg">開始學習</a>
    </div>
</div>

<section id="about">
    <div class="padding">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <img src="{% static "img/python-s.png" %}">
                </div>

                <div class="col-sm-6 text-center">
                    <h2>讓你燃起學Python的熱情</h2>
                    <p class="lead">
                        總是在學習新的程式語言時，特別去注意輸出格式嗎?但是在Python裡面不需要!只需要打print'輸入你想輸入的內容'，就可以輕鬆得到輸出結果。減少繁瑣的步驟，也減少學習的負擔感，讓初學者更輕鬆的學習Python!</p>
                    <p class="lead">Easy Coding是為了讓完全沒有基礎的使用者，一步一步帶領使用者寫Python，讓你不再害怕寫程式!</p>
                </div>
            </div>
        </div>
    </div>

    <div class="padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <h4>最貼心的中文化</h4>
                    <p>
                        總是在網路上學習Python的時候，遇到都是英文的教材而感到煩惱嗎?我們的網站，為使用者創作出全中文的教學課程及評量，不必擔心翻譯問題，並省下翻譯的時間，讓使用者安心順利的閱讀並實作讓學習基礎更扎實。</p>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <img src="{% static "img/ch.png" %}" class="img-responsive">
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <h4>基礎的Python教學</h4>
                    <p>害怕一開始學習就碰到範例看不懂、作業寫不出來的窘境嗎?本網站的課程難易度是隨著使用者的進度慢慢改變的，讓使用者從0開始學習，避免基礎沒打好，還壞了學習程式語言的熱情。</p>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <img src="{% static "img/python.png" %}" class="img-responsive">
                </div>
            </div>
        </div>
    </div>
</section>

<div id="fixed">

</div>

<div class="padding">
    <div class="container">
        <div class="row">

            <div class="col-md-6">
                <img src="{% static "img/python-p.png" %}">
            </div>

            <div class="col-md-6">
                <h2>為什麼是Python?</h2>
                <img src="{% static "img/vs4.png" %}" class="img-responsive">
            </div>

        </div>
    </div>
</div>

<!--footer-->
<footer class="container-fluid text-cener">
    <div class="row">
        <div class="col-lg-3 col-sm-2 col-1"></div>

        <div class="col-lg-4 col-sm-4 col-5">
            <h3>關於我們</h3><br>
            <h4>國立台中科技大學 資訊管理科</h4>
        </div>

        <div class="col-lg-2 col-sm-4 col-5">
            <img src="{% static "img/p.png" %}" class="icon" width=100>
        </div>
    </div>
</footer>

<script src="{% static 'js/menu.js' %}"></script>

</body>

</html>

templates/menu.html
<!DOCTYPE html>
<html>

<head>
    <title>Easy Coding</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--.css-->
    <link rel="stylesheet" href="boot/bootstrap-4.0.0.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="css/global/menu.css" rel="stylesheet">


    <!--.js-->
    <script src="boot/jquery-3.2.1.min.js"></script>
    <script src="boot/bootstrap-4.0.0.js"></script>
</head>

<body>

    <!--menu-->
    <nav id="menu" class="navbar navbar-expand-md fixed-top ">
        <div class="container-fluid">
            <a class="navbar-brand" href="home.html">
                <img src="img/w3newbie2.png" width="150px">
            </a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#meun-collapse" style="margin-right: 15px">
                <div class="menu-toggle">
                    <span class="menu-toggle-grippy"></span>
                </div>
            </button>

            <div class="collapse navbar-collapse" id="meun-collapse">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="profile.html">個人檔案</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="lesson.html">課程</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="editor.html">作業</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="contact.html">聯繫</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!--contain start-->
    <!--contain end-->

    <!--footer-->
    <footer class="container-fluid text-cener">
        <div class="row justify-content-center align-items-center">
            <div class="col-lg-4 col-sm-4 col-5">
                <h3>關於我們</h3><br>
                <h4>國立台中科技大學 資訊管理科</h4>
            </div>

            <div class="col-lg-2 col-sm-4 col-5">
                <div class="row justify-content-center">
                    <img src="img/p.png" class="icon">
                </div>
            </div>
        </div>
    </footer>



    <script src="js/menu.js"></script>
</body>

</html>